# Generated by Django 5.0.1 on 2024-04-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=1, upload_to='photo'),
            preserve_default=False,
        ),
    ]
