# Generated by Django 5.0.1 on 2024-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=3000)),
            ],
        ),
    ]
