# Generated by Django 5.0.1 on 2024-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('email', models.CharField(max_length=3000)),
                ('subject', models.TextField(max_length=3000)),
            ],
        ),
    ]
